### ISSUE TITLE
Add optional onChange callback

### ISSUE THREAD

**Issue by dmitry-tk** [braposo/react-text-loop#16]
It would be nice to have something like that for words change action:

```javascript

textChange(textLoopState){
    // do something...
 }

<TextLoop onChange={textChange}>
    {wordsObj}
</TextLoop>
```

My proposal:

```diff
// TextLoop.jsx
 tick = () => {
        this.setState((state, props) => {
+            if(this.props.onChange){
+              this.props.onChange(state);
+            }

             ...

        });
 };
```

**Comment by braposo** [comment]
Hi @dmitry-tk, sorry for the delay but it seems like a sensible proposal. I've been making some improvements to the library, but just didn't have the time to put everything together and make a new release. 

I'll definitely add this to the API, but if you want to contribute please feel free to open a PR!

**Comment by braposo** [comment]
`onChange` callback is now supported on [v2.0.0](https://github.com/braposo/react-text-loop/releases/tag/v2.0.0)
