### ISSUE TITLE
Server Render Not Possible Due to Window

### ISSUE THREAD

**Issue by khoerling** [braposo/react-text-loop#29]
Please fix when possible and thank you for the awesome software:

ReferenceError: window is not defined
    at ./node_modules/react-text-loop/lib/utils.js:9:3

**Comment by braposo** [comment]
Hi @khoerling, thanks for submitting your issue! 

Can you give a more detailed example of how you're trying to use this? Is it in a NextJS app? Just trying to understand the use-case so we can fix that for everyone else!

**Comment by braposo** [comment]
This has been fixed by `v2.0.1`, can you please confirm @khoerling? Thanks!

**Comment by khoerling** [comment]
That was quick, works flawlessly-- danke schöne.

**Comment by atulmy** [comment]
I'm getting following warning:
```
Warning: Prop `className` did not match. Server: "x0 x3 x4 x7" Client: "x1 x4 x5 x6"
```
which is leading to improper alignment of the text. Any way to fix this?
