### ISSUE TITLE
Code example in readme uses unknown components

### ISSUE THREAD

**Issue by zeroskillz** [braposo/react-text-loop#33]
This block of code in the readme uses a `<Link/>` and `<BodyText/>` component of unknown origin. I suggest replacing them with standard html tags
```
import TextLoop from "react-text-loop";

class App extends Component {
    render() {
        return (
            <h2>
                <TextLoop>
                    <span>First item</span>
                    <Link to="/">Second item</Link>
                    <BodyText>Third item</BodyText>
                </TextLoop>{" "}
                and something else.
            </h2>
        );
    }
}
```

**Comment by braposo** [comment]
@zeroskillz Thanks for opening the issue and the PR. Sorry it took me so long to reply but I ended up not spending much time around this. 

The use of the `Link` and `BodyText` components is to highlight the fact that you can use normal HTML elements (the `span`), something from a 3rd party library or another component in your codebase.

I've made it a bit more explicit in the README so hopefully that will clear any confusion people might have.
