### ISSUE TITLE
Code Sandbox examples are broken

### ISSUE THREAD

**Issue by curtisupshall** [braposo/react-text-loop#37]

**Comment by arhoy** [comment]
any fix on this?

**Comment by braposo** [comment]
Hi @curtisupshall! Thanks for opening the issue. I think this is something weird with codesandbox actually. If you just do any change on the file in the sandbox (a space is enough) it will load the page fine, but it seems to be happening when you first load the page.

I'll take this to the codesandbox team to see if there's something I'm doing wrong but in the meantime let me know if you can't get to the examples like that.

**Comment by braposo** [comment]
This seems to have been fixed now so I'm closing the issue. If it's still failing for anyone we can open it again.
