### ISSUE TITLE
"No tests available"

### ISSUE THREAD

**Issue by thatzacdavis** [braposo/react-text-loop#39]
Would you mind if I started by adding in some basic tests?

**Comment by braposo** [comment]
hey @thatzacdavis that sounds amazing! I wanted to add more robustness to the long for a long time, but only managed to convert it to TS so far. Having tests would be great!

Let me know how that goes, ideally it would use jest + react-testing-library if you test any UI components.

Thanks!

**Comment by thatzacdavis** [comment]
That's my specialty! Be on the lookout for a PR this week.

**Comment by thatzacdavis** [comment]
Of course! Happy to help, and provide a jumping off point. I hope to be able to start doing more "real" tests now as well.
