### ISSUE TITLE
componentWillReceiveProps warning with React 16.9

### ISSUE THREAD

**Issue by erwanriou** [braposo/react-text-loop#44]
Due to the use of react-motion, this library have issue with the componentWillReceiveProps warning and might be deprecated in a further version of react.

I suggest to enhance the project to avoid using react-motion that seems an abandonned project. See below the link of the issue on react-motion that haven't been fix.

https://github.com/chenglou/react-motion/issues/569

why not trying using this library instead? https://github.com/react-spring/react-spring

**Comment by braposo** [comment]
Hey @erwanriou, thanks for opening the issue!

Yes I've thought a few times about that over the years (https://github.com/braposo/react-text-loop/issues/7) but haven't had the time and the need to create a new version with a different library.

I'll probably do that soon though as it makes sense to use the benefits of hooks as well so there will probably be a new major version at some point that can only be used in React 16.3+

**Comment by erwanriou** [comment]
Cool! Yeah lets make the transition to the hooks :)

**Comment by jacobclyne** [comment]
Any updates for this issue?

**Comment by jacksonblankenship** [comment]
I'm still getting this warning in the console, any plans to fix?

**Comment by braposo** [comment]
Sorry, haven't been able to focus on this library in the past months but I'm now back to work on v3 so this will be fixed as part of that update.
