### ISSUE TITLE
Don't loop the text

### ISSUE THREAD

**Issue by lightninglu10** [braposo/react-text-loop#49]
Hey guys, is there a way to not loop the text? Just go through the array and stop?

**Comment by eggsy84** [comment]
A little workaround..... using the timings array and set the time for your last element to be long enough that people wont see it

**Comment by braposo** [comment]
hey @lightninglu10, thanks for your question.

You can use the `interval` option to control the behaviour of the loop.

If you have a timeout that set the interval to 0 after a `options * interval` amount of time it should work.

```js
useEffect(() => {
    const intervalStopTimeout = setTimeout(() => {
      setInterval(0);
      console.log("stop");
    }, options.length * interval); // this is what you should customise

    return () => {
      clearTimeout(intervalStopTimeout);
    };
}, []);
```

See the "Controlled" example in the playground for inspiration: https://codesandbox.io/s/react-text-loop-playground-br4q1?file=/src/App.tsx:2157-3303

**Comment by braposo** [comment]
@lightninglu10 going to close this but aiming to include more explicit options to control the number of loops in the plans for v3

**Comment by shamoons** [comment]
Any update?
