### ISSUE TITLE
Async data will not render

### ISSUE THREAD

**Issue by emilnewel** [braposo/react-text-loop#50]
Hi,

Great package btw!
I'm having some issues with rendering when it comes to async data. 

I'm trying to render the following:
```javascript
const InfoDisplay = () => {
  const [data, setData] = useState({});

  useEffect(() => {
    async function fetchInfo() {
      const result = await axios
        .get(`${API_URI}/info`)
        .then((resp) => resp.data)
        .catch((err) => [{
          error: err.response,
        }]);

      setData(result);
    }

    fetchInfo();
  }, []);
  return (
    <>
      <TextLoop>
        {
          Object.keys(data).map((index) => {
            return <InfoDisplayItem key={index} data={data[index]} />
          })
        }
      </TextLoop>{" "}
    </>
  );
};
```

But nothing shows. However when I either remove the `<TextLoop><TextLoop>` or just use some of the examples given in the README I see stuff rendering. Any ideas why async data won't render?

**Comment by exsesx** [comment]
Any luck on resolving this one?

**Comment by exsesx** [comment]
@emilnewel I solved the problem with a simple conditional render. In other words, just checking that the array of children is not empty.

**Comment by braposo** [comment]
Thanks for replying @exsesx! I haven't had the chance to look into this yet @emilnewel, I'll probably do that over the weekend but for now you can use what @exsesx is suggesting.

This seems to be related with how the new child elements are added to the component but can't know for sure without digging in the code.

**Comment by emilnewel** [comment]
Thanks @exsesx ! 

This worked perfectly. 😄

**Comment by armspkt** [comment]
@braposo Is there alternative solution except conditional render?

thanks.
